version: '3.3'

networks:
  proxynet:
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

services:
  nginx:
    hostname: nginx
    container_name: nginx-sunshine
    image: nginx:1.13
    restart: always
    ports:
      - "90:90"
      - "554:554"
    depends_on:
      - authorization-service
    networks:
      - proxynet
  authorization-service:
    hostname: authorization-service
    image: 'sunshine/authorization-service'
    container_name: authorization-service
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    expose:
      - 8080
    stdin_open: true
    tty: true
    networks:
      - proxynet

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    networks:
      - proxynet
